import { BLOCK } from '../engine/voxel/palette'

export const STRUCTURE_MATERIALS = {
    grass: BLOCK.grass,
    grass2: BLOCK.grass,
    dirt: BLOCK.dirt,
    path: BLOCK.sand,
    sand: BLOCK.sand,
    wood: BLOCK.wood,
    woodDark: BLOCK.woodDark,
    plank: BLOCK.plank,
    bark: BLOCK.bark,
    barkDark: BLOCK.barkDark,
    barkLight: BLOCK.barkLight,
    leaf: BLOCK.leaf,
    leaf2: BLOCK.leaf,
    leafDark: BLOCK.leafDark,
    leafLight: BLOCK.leafLight,
    deepLeaf: BLOCK.deepLeaf,
    fruit: BLOCK.fruit,
    flower: BLOCK.flower,
    mushroom: BLOCK.mushroom,
    wall: BLOCK.wall,
    plaster: BLOCK.plaster,
    stone: BLOCK.stone,
    stone2: BLOCK.stone2,
    darkStone: BLOCK.darkStone,
    roof: BLOCK.roof,
    roofDark: BLOCK.roofDark,
    thatch: BLOCK.thatch,
    trim: BLOCK.trim,
    glass: BLOCK.glass,
    door: BLOCK.door,
    metal: BLOCK.metal,
    banner: BLOCK.banner,
    moss: BLOCK.moss,
    smoke: BLOCK.smoke,
    fire: BLOCK.fire,
} as const

export const STRUCTURAL_BLOCKS = new Set<number>([
    STRUCTURE_MATERIALS.wood,
    STRUCTURE_MATERIALS.woodDark,
    STRUCTURE_MATERIALS.bark,
    STRUCTURE_MATERIALS.barkDark,
    STRUCTURE_MATERIALS.barkLight,
    STRUCTURE_MATERIALS.wall,
    STRUCTURE_MATERIALS.plaster,
    STRUCTURE_MATERIALS.stone,
    STRUCTURE_MATERIALS.stone2,
    STRUCTURE_MATERIALS.darkStone,
    STRUCTURE_MATERIALS.roof,
    STRUCTURE_MATERIALS.roofDark,
    STRUCTURE_MATERIALS.thatch,
    STRUCTURE_MATERIALS.trim,
    STRUCTURE_MATERIALS.door,
    STRUCTURE_MATERIALS.metal,
])

export const LEAF_BLOCKS = new Set<number>([
    STRUCTURE_MATERIALS.leaf,
    STRUCTURE_MATERIALS.leaf2,
    STRUCTURE_MATERIALS.leafDark,
    STRUCTURE_MATERIALS.leafLight,
    STRUCTURE_MATERIALS.deepLeaf,
])
